[package]
name = "gitspore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.22", features = ["json"] }
tokio = { version = "1.34.0", features = ["full"] }
futures = "0.3.29"
serde = { version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
config = {version = "0.13.1", features = ["json5"] }
indicatif = "0.17.7"
